# Generated by Django 6.0.2 on 2026-03-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_trial_lesson_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('subject', models.CharField(blank=True, help_text='Leave blank for any subject', max_length=50)),
                ('max_bookings', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='TrialLessonBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ent_math', 'ENT Mathematics'), ('ent_kazakh', 'ENT Kazakh'), ('ent_russian', 'ENT Russian'), ('ent_history', 'ENT History of Kazakhstan'), ('ielts', 'IELTS'), ('sat_math', 'SAT Mathematics'), ('sat_english', 'SAT English'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('other', 'Other')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_bookings', to='hr.trialslot')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'slot')},
            },
        ),
    ]
