# Generated by Django 6.0.2 on 2026-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triallessonbooking',
            name='subject',
            field=models.CharField(choices=[('ent_math', 'ЕНТ Математика'), ('ent_kazakh', 'ЕНТ Казахский язык'), ('ent_russian', 'ЕНТ Русский язык'), ('ent_history', 'ЕНТ История Казахстана'), ('ielts', 'IELTS'), ('sat_math', 'SAT Математика'), ('sat_english', 'SAT Английский'), ('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('english', 'Английский язык'), ('kazakh', 'Казахский язык'), ('russian', 'Русский язык'), ('history', 'История'), ('geography', 'География'), ('informatics', 'Информатика'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='triallessonrequest',
            name='subject',
            field=models.CharField(choices=[('ent_math', 'ЕНТ Математика'), ('ent_kazakh', 'ЕНТ Казахский язык'), ('ent_russian', 'ЕНТ Русский язык'), ('ent_history', 'ЕНТ История Казахстана'), ('ielts', 'IELTS'), ('sat_math', 'SAT Математика'), ('sat_english', 'SAT Английский'), ('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('english', 'Английский язык'), ('kazakh', 'Казахский язык'), ('russian', 'Русский язык'), ('history', 'История'), ('geography', 'География'), ('informatics', 'Информатика'), ('other', 'Другое')], max_length=50),
        ),
    ]
